name: 'r2py'
description: 'Convert R code to python with rpy2'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  repo-name:
    description: 'Repository Name'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'